In [2]:
!pip install --user pandas

Requirement already satisfied: pandas in /nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages (from pandas) (2.7.3)
Requirement already satisfied: numpy>=1.9.0 in /nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages (from pandas) (1.15.0)
Requirement already satisfied: pytz>=2011k in /nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages (from pandas) (2018.5)
Requirement already satisfied: six>=1.5 in /nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

In [2]:
import pandas as pd

data = pd.read_csv("../Downloads/cwfis_fwi2017.csv")

data.head(10)

/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/nfs/2017/t/thomkim/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters

,aes,wmo,rep_date,temp,td,rh,ws,wg,wdir,pres,...,sog,ffmc,dmc,dc,bui,isi,fwi,dsr,opts,calcstatus
0,1012475,71031,2017-01-01 12:00:00,4.0,-3.7,57.0,50.2,57.8,19,1007.20,...,0.00,62.7,0.2,1.4,0.3,6.0,2.1,0.1,IDW=R:M=1:,1
1,1012710,71798,2017-01-01 12:00:00,4.7,-6.8,43.0,20.7,31.9,29,1007.90,...,0.00,60.8,0.6,1.6,0.6,1.2,0.3,0.0,M=1:,1
2,1013998,719143,2017-01-01 12:00:00,4.6,-5.9,47.9,39.0,50.0,57,1008.07,...,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDW=T:RH:R:M=1:,-3
3,1014820,71774,2017-01-01 12:00:00,0.4,-6.5,60.0,29.7,NaN,20,1006.80,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDW=WSD:R:M=1:,-3
4,1016640,71778,2017-01-01 12:00:00,4.7,-5.2,49.0,57.1,65.6,28,1007.20,...,0.00,65.4,0.3,2.0,0.4,9.5,3.9,0.3,IDW=R:M=1:,1
5,1017099,71914,2017-01-01 12:00:00,0.8,-5.0,65.0,6.2,15.3,2,1007.80,...,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M=1:,-3
6,1017101,71473,2017-01-01 12:00:00,2.9,-2.5,67.0,39.5,45.8,6,1009.10,...,0.00,53.1,0.1,1.1,0.2,1.7,0.4,0.0,M=1:,1
7,1017254,71780,2017-01-01 12:00:00,4.0,-4.9,52.0,13.4,30.6,92,1008.10,...,0.00,38.1,0.2,0.4,0.1,0.0,0.0,0.0,M=1:,1
8,1018598,71783,2017-01-01 12:00:00,3.8,-6.3,48.0,21.6,41.5,12,1008.40,...,0.00,55.5,0.2,0.8,0.3,0.9,0.2,0.0,M=1:,1
9,1018611,71200,2017-01-01 12:00:00,3.3,-5.7,51.0,33.2,54.4,29,1007.90,...,0.00,58.3,0.2,0.9,0.3,1.9,0.4,0.0,M=1:,1

In [3]:
df = data.dropna()

In [4]:
df.head()

,aes,wmo,rep_date,temp,td,rh,ws,wg,wdir,pres,...,sog,ffmc,dmc,dc,bui,isi,fwi,dsr,opts,calcstatus
0,1012475,71031,2017-01-01 12:00:00,4.0,-3.7,57.0,50.2,57.8,19,1007.2,...,0.0,62.7,0.2,1.4,0.3,6.0,2.1,0.1,IDW=R:M=1:,1
1,1012710,71798,2017-01-01 12:00:00,4.7,-6.8,43.0,20.7,31.9,29,1007.9,...,0.0,60.8,0.6,1.6,0.6,1.2,0.3,0.0,M=1:,1
4,1016640,71778,2017-01-01 12:00:00,4.7,-5.2,49.0,57.1,65.6,28,1007.2,...,0.0,65.4,0.3,2.0,0.4,9.5,3.9,0.3,IDW=R:M=1:,1
6,1017101,71473,2017-01-01 12:00:00,2.9,-2.5,67.0,39.5,45.8,6,1009.1,...,0.0,53.1,0.1,1.1,0.2,1.7,0.4,0.0,M=1:,1
7,1017254,71780,2017-01-01 12:00:00,4.0,-4.9,52.0,13.4,30.6,92,1008.1,...,0.0,38.1,0.2,0.4,0.1,0.0,0.0,0.0,M=1:,1

In [5]:
df['fire_percentage'] = (df['fwi']/30)*100

/nfs/2017/t/thomkim/.brew/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
df.head()

,aes,wmo,rep_date,temp,td,rh,ws,wg,wdir,pres,...,ffmc,dmc,dc,bui,isi,fwi,dsr,opts,calcstatus,fire_percentage
0,1012475,71031,2017-01-01 12:00:00,4.0,-3.7,57.0,50.2,57.8,19,1007.2,...,62.7,0.2,1.4,0.3,6.0,2.1,0.1,IDW=R:M=1:,1,7.000000
1,1012710,71798,2017-01-01 12:00:00,4.7,-6.8,43.0,20.7,31.9,29,1007.9,...,60.8,0.6,1.6,0.6,1.2,0.3,0.0,M=1:,1,1.000000
4,1016640,71778,2017-01-01 12:00:00,4.7,-5.2,49.0,57.1,65.6,28,1007.2,...,65.4,0.3,2.0,0.4,9.5,3.9,0.3,IDW=R:M=1:,1,13.000000
6,1017101,71473,2017-01-01 12:00:00,2.9,-2.5,67.0,39.5,45.8,6,1009.1,...,53.1,0.1,1.1,0.2,1.7,0.4,0.0,M=1:,1,1.333333
7,1017254,71780,2017-01-01 12:00:00,4.0,-4.9,52.0,13.4,30.6,92,1008.1,...,38.1,0.2,0.4,0.1,0.0,0.0,0.0,M=1:,1,0.000000

In [7]:
df = df.drop(['aes', 'wmo', 'rep_date', 'td', 'wg', 'wdir', 'pres', 'vis', 'rndays', 'sog', 'ffmc', 'dmc', 'dc', 'bui', 'isi', 'dsr', 'opts', 'calcstatus'], axis=1)

In [8]:
df.head(20)

      temp    rh    ws  precip  fwi  fire_percentage
0      4.0  57.0  50.2    3.11  2.1         7.000000
1      4.7  43.0  20.7    1.20  0.3         1.000000
4      4.7  49.0  57.1    2.73  3.9        13.000000
6      2.9  67.0  39.5    4.00  0.4         1.333333
7      4.0  52.0  13.4    6.20  0.0         0.000000
8      3.8  48.0  21.6    3.30  0.2         0.666667
9      3.3  51.0  33.2    3.20  0.4         1.333333
10     3.8  43.0  44.2    4.00  0.9         3.000000
20     1.8  44.5  47.6    0.80  2.4         8.000000
38     2.4  46.0  31.5    5.20  0.0         0.000000
707    6.0  93.4  29.6    0.00  0.1         0.333333
721   -1.0  73.3   6.4   15.50  0.0         0.000000
752    0.3  44.0  58.7    0.01  7.7        25.666667
755    1.2  33.0  21.5    0.00  0.3         1.000000
1455   0.0  74.8  33.3    8.70  0.0         0.000000
1469   0.4  95.8  23.5    9.80  0.0         0.000000
2205   1.0  64.6  14.8    0.00  0.1         0.333333
2219  -3.0  83.7  24.1    0.00  0.0         0.000000
2266   5.0  61.4  10.0    0.00  0.6         2.000000
2955   8.0  93.5  53.7    3.30  0.1         0.333333

In [9]:
df.shape

(93398, 6)

In [10]:
df.to_csv("fwidataset2017")

In [34]:
!ls

cwfis_fwi2016.csv   data cleaning.ipynb fwidataset2017